name: brownaming
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - biopython=1.84=py311h331c9d8_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - diamond=2.1.13=h13889ed_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libblas=3.9.0=36_h4a7cf45_openblas
  - libcblas=3.9.0=36_h0358290_openblas
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgomp=15.1.0=h767d61c_5
  - liblapack=3.9.0=36_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libuuid=2.41.1=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - numpy=2.3.3=py311h2e04523_0
  - openssl=3.5.3=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.11.13=h9e4cc4f_0_cpython
  - python_abi=3.11=8_cp311
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.60.1
      - idna==3.10
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.6
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - six==1.17.0
      - threadpoolctl==3.6.0
      - tzdata==2025.2
      - urllib3==2.5.0
